version: '3.8'

services:

  ############# Generals #############
  postgres:
    image: postgres:13.0-alpine
    container_name: postgres
    volumes:
      - ./.data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - backend
    env_file:
      - ./src/.env

  redis:
    image: redis:6.2.6
    container_name: redis
    command:
      - redis-server
    ports:
      - 6379:6379
    networks:
      - backend
    env_file:
      - ./src/.env

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - 80:80
    depends_on:
      - flask-auth
    networks:
      - backend

  flask-auth:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flask-auth
    command: gunicorn wsgi_app:app -b 0.0.0.0:5000 --reload
    expose:
     - 5000
    depends_on:
      - redis
      - postgres
    env_file:
      - ./src/.env
    networks:
      - backend




volumes:
  postgres_volume:

networks:
  backend:
    driver: bridge