version: '3.8'

services:

############# Generals #############
  postgres:
    image: postgres:13.0-alpine
    container_name: postgres
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - backend
    env_file:
      - .env

  redis:
    image: redis:6.2.6
    container_name: redis
    command:
      - redis-server
    ports:
      - 6379:6379
    networks:
      - backend
    env_file:
      -  .env



volumes:
  postgres_volume:

networks:
  backend:
    driver: bridge