""" Constants for /flask-auth service"""

JWT_PREFIX = "Bearer "

MSG_FIELD_CANNOT_BE_BLANK = "This field cannot be blank."
MSG_USER_ALREADY_EXIST = "A user with that username already exists"
MSG_USER_CREATED_SUCCESSFULLY = "User created successfully."
MSG_USER_NOT_FOUND = "user not found"
MSG_USER_DELETED = "user deleted"
MSG_UNSUFFICIENT_CREDENTIALS = "insufficient credentials"
MSG_PASSWORD_CHANGED_SUCCESSFULLY = "password changed successfully"
MSG_USER_NOT_FOUND_OR_INCORRECT_PASSWORD = "User not found or incorrect password"
MSG_INVALID_CREDENTIALS = "Invalid credentials"
MSG_TOKEN_ALREADY_REVOKED = "Token already revoked"
MSG_INVALID_TOKEN = "Invalid token"
